#!/usr/bin/env python3
"""Remove bogus uint32_t declarations added by comprehensive_fix.py."""
import re, os

SRC = "/home/gzr/new_test/gem5/src/custom/riscv"

# English words and other non-variable names that might have been added
ENGLISH_WORDS = frozenset({
    'a', 'an', 'the', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'has', 'have', 'had', 'do', 'does', 'did', 'will', 'would', 'could', 'should',
    'may', 'might', 'can', 'shall', 'need', 'dare', 'ought', 'used',
    'not', 'no', 'nor', 'none', 'nothing', 'nobody', 'nowhere',
    'all', 'any', 'some', 'every', 'each', 'both', 'few', 'many', 'much',
    'more', 'most', 'other', 'another', 'several', 'such', 'own', 'same',
    'this', 'that', 'these', 'those', 'it', 'its', 'they', 'them', 'their',
    'we', 'us', 'our', 'you', 'your', 'he', 'him', 'his', 'she', 'her',
    'who', 'whom', 'which', 'what', 'whose', 'whoever', 'whatever',
    'here', 'there', 'where', 'when', 'why', 'how', 'then', 'than',
    'also', 'too', 'very', 'just', 'only', 'even', 'still', 'already',
    'yet', 'once', 'again', 'ever', 'never', 'always', 'often', 'usually',
    'sometimes', 'rarely', 'seldom', 'maybe', 'perhaps', 'probably',
    'certainly', 'definitely', 'absolutely', 'literally', 'basically',
    'actually', 'essentially', 'effectively', 'approximately', 'roughly',
    'about', 'around', 'between', 'among', 'through', 'throughout',
    'above', 'below', 'before', 'after', 'during', 'within', 'without',
    'across', 'along', 'behind', 'beneath', 'beside', 'beyond', 'inside',
    'outside', 'under', 'upon', 'via', 'with', 'without', 'toward',
    'towards', 'onto', 'into', 'onto', 'upon', 'while', 'although',
    'though', 'because', 'since', 'unless', 'until', 'whether',
    'despite', 'regardless', 'if', 'else', 'then', 'so', 'as',
    'like', 'unlike', 'including', 'excluding', 'except', 'but',
    'or', 'and', 'nor', 'for', 'yet', 'so', 'because', 'since',
    'before', 'after', 'until', 'while', 'when', 'where', 'why',
    'how', 'what', 'which', 'who', 'whom', 'whose', 'that',
    'note', 'important', 'see', 'example', 'i.e', 'e.g', 'etc',
    'vs', 'versus', 'aka', 'aka_', 'de', 'el', 'la', 'le', 'les',
    'un', 'une', 'des', 'du', 'en', 'au', 'aux', 'sur', 'dans',
    'pour', 'par', 'avec', 'sans', 'chez', 'entre', 'depuis',
    'pendant', 'avant', 'apres', 'pres', 'loin', 'contre',
    'car', 'mais', 'donc', 'ni', 'ou', 'où', 'et', 'est', 'sont',
    'ont', 'ont', 'fait', 'faire', 'peut', 'peuvent', 'veut',
    'vouloir', 'savoir', 'connaitre', 'devoir', 'pouvoir',
    'falloir', 'valoir', 'mieux', 'moins', 'plus', 'tres',
    'bien', 'mal', 'bon', 'mauvais', 'grand', 'petit', 'autre',
    'chaque', 'tout', 'tous', 'toute', 'toutes', 'quelque',
    'quelques', 'certain', 'certains', 'certaines', 'plusieurs',
    'meme', 'mêmes', 'autre', 'autres', 'tel', 'telle', 'tels',
    'telles', 'nul', 'nulle', 'nuls', 'nulles',
    'must', 'shall', 'should', 'will', 'would', 'can', 'could',
    'may', 'might', 'ought', 'need', 'dare',
    'let', 'lets', 'let_s', 'suppose', 'assume', 'consider',
    'define', 'call', 'called', 'named', 'known', 'given', 'taken',
    'respectively', 'respectively_', 'therefore', 'however',
    'furthermore', 'moreover', 'nevertheless', 'nonetheless',
    'consequently', 'hence', 'thus', 'thereby', 'accordingly',
    'meanwhile', 'likewise', 'similarly', 'conversely', 'instead',
    'otherwise', 'namely', 'specifically', 'particularly',
    'especially', 'notably', 'typically', 'commonly', 'generally',
    'normally', 'usually', 'traditionally', 'conventionally',
    'standard', 'typical', 'normal', 'common', 'usual', 'regular',
    'correct', 'incorrect', 'proper', 'improper', 'appropriate',
    'inappropriate', 'valid', 'invalid', 'legal', 'illegal',
    'true', 'false', 'yes', 'no', 'on', 'off', 'high', 'low',
    'input', 'output', 'inout', 'dir', 'direction',
    'clock', 'clk', 'reset', 'rst', 'enable', 'en',
    'posedge', 'negedge', 'pos', 'neg', 'edge',
    'async', 'sync', 'synchronous', 'asynchronous',
    'combinational', 'combinatorial', 'sequential',
    'registered', 'latched', 'wire', 'reg', 'logic',
    'flip', 'flop', 'flipflop', 'register', 'latch',
    'synthesis', 'elaboration', 'simulation',
    'verilog', 'systemverilog', 'vhdl', 'vlog',
    'block', 'blocks', 'blocking', 'nonblocking',
    'assignment', 'assign', 'always', 'initial', 'final',
    'module', 'endmodule', 'instance', 'instantiation',
    'port', 'ports', 'signal', 'signals', 'net', 'nets',
    'continuous', 'procedural', 'behavioral', 'structural',
    'rtl', 'gate', 'gate_level', 'transistor',
    'casex', 'casez', 'endcase', 'default', 'end',
    'for', 'generate', 'endgenerate', 'ifdef', 'ifndef',
    'define', 'undef', 'include', 'timescale',
    'begin', 'end', 'fork', 'join', 'repeat',
    'wait', 'event', 'triggered', 'posedge', 'negedge',
    'or', 'and', 'nand', 'nor', 'xor', 'xnor',
    'buf', 'not', 'bufif0', 'bufif1', 'notif0', 'notif1',
    'cmos', 'nmos', 'pmos', 'rcmos', 'rnmos', 'rpmos',
    'tran', 'tranif0', 'tranif1', 'rtran', 'rtranif0', 'rtranif1',
    'pullup', 'pulldown', 'supply0', 'supply1', 'tri', 'tri0', 'tri1',
    'triand', 'trior', 'trireg', 'wand', 'wor',
    'integer', 'real', 'realtime', 'time',
    'signed', 'unsigned', 'scalared', 'vectored',
    'supply', 'strong', 'pull', 'weak', 'large', 'medium', 'small',
    'highz0', 'highz1', 'small', 'medium', 'large',
    'specify', 'endspecify', 'pulsestyle_onevent',
    'pulsestyle_ondetect', ' showcancelled', 'noshowcancelled',
    'pathtonand', 'nopathtonand',
    'get', 'gets', 'set', 'sets', 'put', 'puts',
    'add', 'sub', 'mul', 'div', 'mod', 'rem',
    'inc', 'dec', 'increment', 'decrement',
    'shift', 'rotate', 'left', 'right', 'arithmetic', 'logical',
    'barrel', 'barrel_shifter', 'adder', 'subtractor',
    'multiplier', 'divider', 'comparator', 'multiplexer',
    'mux', 'demux', 'decoder', 'encoder', 'priority',
    'counter', 'accumulator', 'register_file', 'memory', 'ram', 'rom',
    'fifo', 'lifo', 'stack', 'queue', 'buffer', 'cache',
    'pipeline', 'stage', 'stages', 'execute', 'fetch', 'decode',
    'writeback', 'memory', 'issue', 'commit', 'retire',
    'flush', 'stall', 'bubble', 'forward', 'bypass',
    'branch', 'jump', 'call', 'return', 'trap', 'interrupt',
    'exception', 'fault', 'error', 'status', 'control',
    'data', 'address', 'addr', 'value', 'values', 'index',
    'offset', 'base', 'limit', 'bound', 'range', 'size',
    'length', 'width', 'depth', 'count', 'total', 'number',
    'bit', 'bits', 'byte', 'bytes', 'word', 'words', 'dword',
    'half', 'halfword', 'double', 'doubleword', 'quad',
    'nibble', 'octet', 'field', 'fields', 'mask', 'masks',
    'pattern', 'patterns', 'flag', 'flags', 'tag', 'tags',
    'entry', 'entries', 'item', 'items', 'element', 'elements',
    'row', 'rows', 'col', 'cols', 'column', 'columns',
    'line', 'lines', 'set', 'sets', 'way', 'ways', 'bank', 'banks',
    'port_a', 'port_b', 'port_c', 'port_d',
    'read', 'write', 'rw', 'access', 'hit', 'miss', 'evict',
    'allocate', 'deallocate', 'fill', 'invalidate', 'flush',
    'clean', 'dirty', 'valid', 'invalid', 'shared', 'exclusive',
    'modified', 'owned', 'transient', 'pending',
    'request', 'response', 'grant', 'release', 'ack', 'nack',
    'arbitration', 'arbiter', 'priority', 'round_robin',
    'fixed', 'dynamic', 'static', 'flexible',
    'master', 'slave', 'manager', 'subordinate',
    'initiator', 'target', 'requester', 'responder',
    'transaction', 'beat', 'burst', 'packet', 'frame',
    'protocol', 'interface', 'bus', 'channel', 'link',
    'serial', 'parallel', 'pipeline', 'pipelined',
    'single', 'multiple', 'dual', 'triple', 'quad',
    'simple', 'complex', 'compound', 'composite',
    'hierarchical', 'flat', 'nested', 'recursive',
    'top', 'bottom', 'left', 'right', 'center', 'middle',
    'front', 'back', 'side', 'edge', 'corner',
    'rising', 'falling', 'both', 'level', 'edge',
    'immediate', 'direct', 'indirect', 'relative', 'absolute',
    'forward', 'backward', 'reverse', 'inverse',
    'up', 'down', 'updown', 'bidirectional',
    'increment', 'decrement', 'increasing', 'decreasing',
    'ascending', 'descending', 'sorted', 'ordered', 'random',
    'any', 'some', 'all', 'none', 'each', 'every',
    'first', 'last', 'next', 'previous', 'current',
    'initial', 'final', 'previous', 'next',
    'start', 'stop', 'begin', 'end', 'init', 'done',
    'ready', 'busy', 'wait', 'hold', 'go', 'step',
    'idle', 'active', 'sleep', 'wake', 'halt',
    'error', 'fatal', 'warning', 'info', 'debug', 'trace',
    'pass', 'fail', 'done', 'timeout', 'abort', 'retry',
    'ok', 'okay', 'success', 'failure', 'status',
    'enabled', 'disabled', 'enable', 'disable',
    'set', 'clear', 'toggle', 'load', 'store', 'capture',
    'update', 'refresh', 'sync', 'lock', 'unlock',
    'protect', 'unprotect', 'secure', 'privileged',
    'user', 'supervisor', 'machine', 'hypervisor',
    'kernel', 'driver', 'firmware', 'software', 'hardware',
    'config', 'configure', 'configuration', 'setup',
    'mode', 'modes', 'state', 'states', 'phase', 'phases',
    'step', 'steps', 'cycle', 'cycles', 'period', 'periods',
    'frequency', 'latency', 'bandwidth', 'throughput',
    'power', 'energy', 'current', 'voltage', 'temperature',
    'area', 'speed', 'performance', 'efficiency',
    'min', 'max', 'avg', 'sum', 'mean', 'median', 'mode',
    'std', 'dev', 'variance', 'correlation',
    'inf', 'nan', 'zero', 'one', 'two', 'three', 'four',
    'five', 'six', 'seven', 'eight', 'nine', 'ten',
    'first', 'second', 'third', 'fourth', 'fifth',
    'single', 'double', 'triple', 'quadruple',
    'once', 'twice', 'thrice',
    'half', 'third', 'quarter', 'fifth',
    'pair', 'dozen', 'score', 'gross',
    'empty', 'null', 'nil', 'void', 'blank',
    'full', 'partial', 'fractional', 'whole',
    'auto', 'manual', 'default', 'custom',
    'standard', 'extended', 'reduced', 'compressed',
    'normal', 'fast', 'slow', 'quick', 'rapid',
    'major', 'minor', 'critical', 'optional',
    'mandatory', 'required', 'optional',
    'explicit', 'implicit', 'inferred',
    'visible', 'invisible', 'hidden', 'exposed',
    'internal', 'external', 'local', 'global',
    'private', 'public', 'protected',
    'shared', 'exclusive', 'locked', 'owned',
    'static', 'dynamic', 'virtual', 'abstract',
    'base', 'derived', 'subtype', 'supertype',
    'concrete', 'abstract',
    'atomic', 'transactional', 'consistent',
    'isolated', 'durable',
    'temporal', 'spatial', 'spatio_temporal',
    'actual', 'formal', 'actual_parameter',
    'actual', 'expected', 'unexpected',
    'intended', 'actual', 'observed',
    'nominal', 'typical', 'worst', 'best',
    'case', 'corner', 'edge',
    'worse', 'better', 'faster', 'slower',
    'equal', 'greater', 'less', 'larger', 'smaller',
    'compare', 'comparison', 'differ', 'difference',
    'same', 'similar', 'different', 'distinct',
    'match', 'mismatch', 'equal', 'unequal',
    'positive', 'negative', 'zero', 'non_zero',
    'nonnegative', 'nonpositive',
    'infinite', 'finite', 'bounded', 'unbounded',
    'saturating', 'wrapping', 'clamping',
    'overflow', 'underflow', 'carry', 'borrow',
    'sign', 'zero', 'parity', 'even', 'odd',
    'complement', 'magnitude', 'absolute',
    'binary', 'decimal', 'hex', 'hexadecimal', 'octal',
    'signed', 'unsigned', 'sign_extend', 'zero_extend',
    'truncate', 'round', 'floor', 'ceil', 'nearest',
    'fractional', 'fixed_point', 'floating_point',
    'ieee', '754', 'single_precision', 'double_precision',
    'half_precision', 'quad_precision',
    'mantissa', 'exponent', 'significand', 'fraction',
    'nan', 'infinity', 'qnan', 'snan',
    'denormal', 'subnormal', 'normalized',
    'mac', 'fma', 'fmac', 'multiply_accumulate',
    'clz', 'ctz', 'popcount', 'bitreverse',
    'rotate', 'shift', 'barrel',
    'and', 'or', 'xor', 'nand', 'nor', 'xnor',
    'not', 'buf', 'buffered', 'invert',
    'mux', 'demux', 'select', 'selector',
    'decode', 'encoder', 'priority_encoder',
    'adder', 'subtractor', 'comparator',
    'multiplier', 'divider', 'square_root',
    'reciprocal', 'inverse',
    'accumulator', 'counter', 'timer',
    'lfsr', 'prng', 'random', 'pseudo_random',
    'crc', 'checksum', 'hash', 'signature',
    'ecc', 'edc', 'parity', 'sec_ded',
    'encoder', 'decoder', 'codec', 'code',
    'gray', 'binary', 'one_hot', 'one_cold',
    'thermometer', 'barrel',
    'synchronizer', 'metastability', 'mtbf',
    'deglitch', 'debounce', 'filter',
    'fifo', 'lifo', 'stack', 'queue',
    'ram', 'rom', 'sram', 'dram', 'cam', 'tcam',
    'register_file', 'rf', 'scratchpad',
    'cache', 'cache_line', 'cache_set', 'cache_way',
    'tag', 'index', 'offset', 'sector',
    'tlb', 'mmu', 'pagetable', 'page_walker',
    'pte', 'pde', 'pge', 'page', 'frame',
    'virtual', 'physical', 'intermediate',
    'translate', 'translation', 'map', 'mapping',
    'protection', 'permission', 'access',
    'readable', 'writeable', 'executable',
    'user_accessible', 'supervisor_only',
    'machine_only', 'hypervisor_only',
    'gem5',
    'keep', 'hold', 'maintain', 'preserve',
    'change', 'modify', 'alter', 'transform',
    'convert', 'cast', 'reinterpret',
    'extract', 'insert', 'remove', 'replace',
    'split', 'merge', 'combine', 'separate',
    'serialize', 'deserialize', 'pack', 'unpack',
    'encode', 'decode', 'compress', 'decompress',
    'encrypt', 'decrypt', 'hash', 'verify',
    'authenticate', 'authorize',
    'compute', 'calculate', 'evaluate',
    'determine', 'find', 'locate', 'search',
    'sort', 'order', 'arrange', 'organize',
    'collect', 'gather', 'accumulate', 'aggregate',
    'distribute', 'scatter', 'broadcast', 'multicast',
    'route', 'steer', 'direct', 'forward',
    'align', 'misalign', 'pad', 'fill',
    'synchronize', 'sync', 'async',
    'schedule', 'dispatch', 'issue', 'commit',
    'retire', 'complete', 'finish', 'done',
    'pending', 'outstanding', 'in_flight',
    'hold', 'release', 'acquire',
    'reserve', 'release', 'lock', 'unlock',
    'arbitrate', 'grant', 'request',
    'prioritize', 'preempt',
    'reorder', 'replay', 'retry', 'reissue',
    'bypass', 'forward', 'bypass_',
    'speculate', 'predict', 'mispredict',
    'correct', 'recover', 'repair',
    'checkpoint', 'snapshot', 'restore',
    'progress', 'forward', 'backward',
    'wave', 'pipeline', 'pipe',
    'super_scalar', 'vliw', 'simd', 'vector',
    'in_order', 'out_of_order',
    'rename', 'remap', 'reorder',
    'scoreboard', 'reservation', 'station',
    'rob', 'reorder_buffer', 'lsq', 'load_store_queue',
    'iq', 'issue_queue', 'instruction_queue',
    'fetch_queue', 'decode_queue',
    'writeback', 'bypass_network',
    'functional_unit', 'fu', 'execution_unit',
    'alu', 'agu', 'bru', 'lsu', 'fpu', 'vpu',
    'mul', 'div', 'shft', 'cmp', 'cvt',
    'clr', 'set', 'rst', 'cnt', 'dec', 'inc',
    'logic', 'arithmetic', 'control', 'datapath',
    'predicate', 'condition', 'conditional',
    'carry', 'borrow', 'overflow', 'underflow',
    'saturation', 'wrap', 'clip', 'clamp',
    'proceed', 'continue', 'do', 'redo', 'undo',
    'toggle', 'trigger', 'pulse', 'edge',
    'counter', 'count', 'counting',
    'timer', 'timeout', 'watchdog',
    'interrupt', 'irq', 'exception', 'fault', 'trap',
    'vector', 'handler', 'service', 'return',
    'nested', 'prioritized', 'vectored',
    'edge_triggered', 'level_triggered',
    'high', 'low', 'rising', 'falling', 'both',
    'programmable', 'configurable',
    'maskable', 'non_maskable', 'nmi',
    'pending', 'active', 'inactive',
    'acknowledge', 'complete', 'retire',
    'deassert', 'assert',
    'clear', 'set', 'toggle', 'pulse',
    'edge_detect', 'glitch', 'debounce',
    'resync', 'resynchronize',
    'crossing', 'domain_crossing',
    'cdc', 'synchronizer',
    'async_fifo', 'sync_fifo',
    'gray_code', 'binary_code',
    'one_hot', 'one_cold',
    'mux', 'demux', 'select',
    'priority', 'arbiter', 'round_robin',
    'fixed', 'dynamic', 'weighted',
    'strict', 'fair', 'lockout',
    'grant', 'request', 'release',
    'master', 'slave', 'multi_master',
    'bus', 'matrix', 'crossbar', 'network',
    'ring', 'mesh', 'torus', 'tree', 'butterfly',
    'banyan', 'omega', 'baseline', 'benes',
    'clos', 'fat_tree', 'flattened',
    'router', 'switch', 'hub', 'bridge',
    'port', 'channel', 'lane', 'link',
    'filt', 'flit', 'packet', 'cell',
    'wormhole', 'store_forward', 'cut_through',
    'virtual_channel', 'vc', 'buffer_class',
    'credit', 'on_off', 'ack_nack',
    'flow_control', 'congestion', 'backpressure',
    'eject', 'inject', 'terminate',
    'serial', 'parallel', 'serdes',
    'encoder', 'decoder', 'scrambler',
    'descrambler', 'de_skew', 'alignment',
    'comma', 'character', 'symbol',
    'byte', 'word', 'dword', 'qword',
    'block', 'frame', 'packet',
    'protocol', 'transaction', 'transfer',
    'read', 'write', 'rw', 'atomic',
    'burst', 'single', 'increment', 'wrap',
    'address', 'data', 'byte_enable',
    'strobe', 'valid', 'ready', 'accept',
    'wait', 'hold', 'error', 'abort',
    'count', 'pointer', 'ptr', 'index',
})

for f in sorted(os.listdir(SRC)):
    if not f.endswith('.cc'):
        continue
    path = os.path.join(SRC, f)
    with open(path) as r:
        lines = r.readlines()
    
    new_lines = []
    removed = 0
    for line in lines:
        # Check if this is a bogus uint32_t declaration
        m = re.match(r'^\s*uint32_t\s+(\w+)\s*=\s*0\s*;\s*$', line)
        if m:
            var_name = m.group(1)
            if var_name in ENGLISH_WORDS:
                removed += 1
                continue
            # Also remove very short names or names that look like comments
            if len(var_name) <= 3 and var_name not in ('pc', 'op', 'reg', 'imm', 'rd_', 'rs1', 'rs2'):
                # Only remove if it's clearly not a Verilog signal name
                if var_name in ('the', 'and', 'for', 'not', 'but', 'was', 'are', 'all', 'any', 'has',
                               'had', 'may', 'can', 'its', 'our', 'you', 'who', 'how', 'why', 'too',
                               'yet', 'get', 'set', 'put', 'add', 'sub', 'div', 'mod', 'rem', 'inc',
                               'dec', 'top', 'bit', 'use', 'old', 'new', 'end', 'run', 'try', 'fix',
                               'lot', 'bad', 'big', 'own', 'non', 'per', 'pre', 'pro', 'mis', 'via'):
                    removed += 1
                    continue
        new_lines.append(line)
    
    if removed > 0:
        with open(path, 'w') as w:
            w.writelines(new_lines)
        print(f"{f}: removed {removed} bogus declarations")
